name: Test & Lint

on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  prepare_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

  lint:
    name: Run linter
    needs: prepare_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run linter
        run: yarn lint

  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: Test all packages
    needs: prepare_dependencies
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build api-client
        run: yarn build:api-client

      - name: Test api-client
        run: yarn test:api-client

      - name: Build composables
        run: yarn build:composables

      - name: Test composables
        run: yarn test:composables

      - name: Build theme
        run: yarn build:theme

      - name: Test theme
        run: yarn test:theme

  test-e2e:
    name: Run all end-to-end tests
    needs: prepare_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Get IP4 address
        run: echo "ip_address=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | head -1)" >> $GITHUB_ENV

      - name: E2E in Chrome
        uses: cypress-io/github-action@v5.0.5
        with:
          browser: chrome
          build: yarn build
          config-file: tests/e2e/cypress.config.js
          project: ${{ github.workspace }}/packages/theme/
          start: ${{ github.workspace }}/node_modules/.bin/concurrently --kill-others "yarn dev:api-client" "yarn dev:composables" "yarn dev:theme --hostname '${{ env.ip_address }}' --port 3000"
          wait-on: 'http://${{ env.ip_address }}:3000'
        env:
          CYPRESS_BASE_URL: 'http://${{ env.ip_address }}:3000'

      - name: Upload code coverage report
        if: ${{ always() && !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: Code Coverage Report
          path: ${{ github.workspace }}/packages/theme/tests/e2e/coverage/lcov-report/

      - name: Add code coverage summary
        if: ${{ always() && !cancelled() }}
        run: |
          jq '.total' ${{ github.workspace }}/packages/theme/tests/e2e/coverage/coverage-summary.json  >> $GITHUB_STEP_SUMMARY
